// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr-lUt8beNb9xfZZSdfDCKrEsKWfegFpY',
    appId: '1:1045478256246:web:b242d2b863d06ea4133957',
    messagingSenderId: '1045478256246',
    projectId: 'redglow-54a5f',
    authDomain: 'redglow-54a5f.firebaseapp.com',
    storageBucket: 'redglow-54a5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwOpcBj0Q-GgBdzmd3WWDHCBCAgW8oQcM',
    appId: '1:1045478256246:android:98fbf039caf4eeb2133957',
    messagingSenderId: '1045478256246',
    projectId: 'redglow-54a5f',
    storageBucket: 'redglow-54a5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKaynI4a5Rzoup6Se3yhx4GG_96tsSAag',
    appId: '1:1045478256246:ios:0f93a3b43c6b045c133957',
    messagingSenderId: '1045478256246',
    projectId: 'redglow-54a5f',
    storageBucket: 'redglow-54a5f.firebasestorage.app',
    iosBundleId: 'br.com.redglow.app',
  );
}
